sudo: required

language: minimal

services:
  - docker

install:
  - '"$TRAVIS_BUILD_DIR/bin/bootstrap"'
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push "$DOCKER_USERNAME/enek-build:latest"

script:
  - docker run --privileged -v "$TRAVIS_BUILD_DIR:/work/enek" -e TERM -e TRAVIS_JOB_NUMBER -e TRAVIS_JOB_ID -e TRAVIS_PULL_REQUEST -w /work/enek -t --rm cryolite/enek-build:latest /work/enek/bin/cibuild-on-travis
