sudo: required

language: cpp

services:
  - docker

before_install:
  - sudo apt-get update
  - sudo apt-get install -y realpath
  - docker pull cryolite/enek-build:latest

script:
  - script/test.sh --docker --build-dir=/work/enek-build --concurrency=auto --debug --enable-coverage
