sudo: required

language: cpp

services:
  - docker

before_install:
- docker pull cryolite/enek-build:latest

script:
- docker run --privileged -v .:/work/enek -w /work/enek --rm -it cryolite/enek-build:latest /work/enek/script/ci.sh /work/enek-build
