sudo: required

language: cpp

services:
  - docker

before_install:
  - docker pull cryolite/enek-build:latest

script:
  - docker run --privileged -v $(pwd):/work/enek -e TRAVIS_JOB_NUMBER -e TRAVIS_JOB_ID -e TRAVIS_PULL_REQUEST -w /work/enek --rm -it cryolite/enek-build:latest script/cibuild.sh
